const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

test("NKNK gallery config is sequential and points at optimized webp assets", () => {
  const source = fs.readFileSync("js/nknk-gallery.js", "utf8");
  const context = vm.createContext({ window: {} });
  vm.runInContext(source, context);
  const gallery = vm.runInContext("NKNK_GALLERY", context);
  assert.ok(Array.isArray(gallery));
  assert.equal(gallery.length, context.window.NKNK_GALLERY.length);
  assert.ok(gallery.length >= 1);
  let total = 0;
  gallery.forEach((item, index) => {
    assert.equal(item.id, index + 1);
    assert.match(item.thumb, /^images\/optimized\/nknk\/\d+\.webp$/);
    assert.match(item.full, /^images\/optimized\/nknk\/full\/\d+\.webp$/);
    assert.ok(fs.existsSync(item.thumb), item.thumb);
    assert.ok(fs.existsSync(item.full), item.full);
    total += fs.statSync(item.thumb).size + fs.statSync(item.full).size;
    const stem = path.basename(item.thumb, ".webp");
    assert.equal(stem, String(item.id));
    const originals = [".jpg", ".jpeg", ".png", ".webp", ".gif"].map((ext) => path.join("NKNK", `${item.id}${ext}`));
    assert.ok(originals.some((file) => fs.existsSync(file)), `missing original for ${item.id}`);
  });
  assert.ok(total < 5 * 1024 * 1024, `gallery assets should stay under 5 MiB, got ${(total / 1024 / 1024).toFixed(2)} MiB`);
});

test("NKNK gallery uses a single-row marquee with accessible lightbox and CSP-safe bindings", () => {
  const html = fs.readFileSync("index.html", "utf8");
  const ui = fs.readFileSync("js/nknk-gallery-ui.js", "utf8");
  const css = fs.readFileSync("style.css", "utf8");
  const gen = fs.readFileSync("tools/generate-nknk-gallery.mjs", "utf8");
  assert.match(html, /id="nknk-gallery"/);
  assert.match(html, /id="nknk-lightbox"/);
  assert.match(html, /js\/nknk-gallery\.js/);
  assert.match(html, /js\/nknk-gallery-ui\.js/);
  assert.doesNotMatch(html, /nknk-gallery-more/);
  assert.doesNotMatch(html, /onclick=/);
  assert.doesNotMatch(ui, /\bonclick\b/);
  assert.doesNotMatch(css, /nknk-gallery-more/);
  assert.match(ui, /ROW_COUNT = 1/);
  assert.match(ui, /translate3d/);
  assert.match(ui, /requestAnimationFrame/);
  assert.match(ui, /prefers-reduced-motion/);
  assert.match(ui, /IntersectionObserver/);
  assert.match(ui, /Mount immediately|mount\(\)/);
  assert.doesNotMatch(ui, /if \(visible\) mount\(\)/);
  assert.match(ui, /aria-hidden/);
  assert.match(ui, /DRAG_THRESHOLD/);
  assert.match(ui, /pointerdown/);
  assert.match(ui, /ArrowLeft/);
  assert.match(ui, /Escape/);
  assert.match(ui, /preloadAdjacent/);
  assert.match(ui, /NKNK 插画/);
  assert.match(css, /mask-image/);
  assert.match(css, /nknk-marquee/);
  assert.match(css, /scroll-snap-type/);
  assert.match(gen, /THUMB_WIDTH = 300/);
  assert.match(gen, /FULL_LONG_EDGE = 1080/);
  assert.match(gen, /metadata/);
});
